### PR TITLE
WIP: Add expression macro for the selector type

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
## Motivation

This is a follow-up on [#1539 ](https://github.com/kube-rs/kube/pull/1539#discussion_r1684587638) which adds a macro for `Expression` type, allowing to avoid unnecessary amount of `into()` calls while constructing a simple static expression.

## Solution

Example:
```rust
expression!("foo" not in "bar", "baz");
// Instead of
Expression::NotIn("foo".into(), ["bar".into(), "baz".into()].into());

expression!("foo" in "bar","baz");
expression!("foo" == "bar");
let array = ["bar".into(), "baz".into()];
expression!("foo" in array);
``` 

To be done:
- [ ] `selector!` macro (can be done?..)

### CODE REVIEW

**Comment by SOF3** [comment]
Probably unpopular opinion, but doesn't this end up making users learn yet another foreign syntax of specifying labels? Right now there are already so many different syntaxes (kubectl CLI, LabelSelector matchLabels, LabelSelector matchExpressions), and we are adding yet another syntax here.

If the sole intention is to avoid the `.into()`s, can we make better `Expression` into-constructors instead? e.g.

```rs
pub struct In<KeyT, ValuesT>(KeyT, ValuesT);
impl<KeyT, ValuesT> From<In<KeyT, ValuesT>> for Expression
where
    KeyT: Into<String>,
    ValuesT: IntoIterator,
    <ValuesT as IntoIterator>::Item: Into<String>,
{ ... }

// vice versa for the other three variants

pub struct Expressions(Vec<Expression>); // instead of a local type alias

impl<T: Into<Expression>> From<T> for Expressions { ... }

impl<T1, T2> From<(T1, T2)> for Expressions
where
    T1: Into<Expression>,
    T2: Into<Expression>,
{ ... }
```

**Comment by clux** [comment]
I have the same reservations as @SOF3 here (even though I did ask for this). I think it because is becoming more of a DSL than a typed convenience, when the primary aim is to get rid of all the `into()` pollution.

if the macro was a little more typed ala:

```diff
+selector::in!("foo", ["bar", "baz"]);
-expression!("foo" in "bar", "baz");
```

then i'd be less concerned. though, if SOF3's solution without macros work:

> ```rust
> let selector: labels::Selector = (
>     labels::In("foo", ["bar"]),
>     labels::Equal("baz", "qux"),
> ).into();
> ```

then that ^ might be a better approach than macros.

**Comment by Danil-Grigorev** [comment]
Yeah, I'm also seeing that this is the limit of macro usage, like selector! is not working for me with the current model. The idea was to give it a feel like writing a raw string (as before), but with typing:
```rust
selector!("foo" in ("bar", "baz"),"env" == "dev");
```

Macros are not giving readable compiler errors and I have the same feeling of a new DSL. Plus you can't easily track in which branch your expression ended up. Was a good exercise though 🙂

**Comment by Danil-Grigorev** [comment]
Closing this to revise later.

**Pull request closed without merging**
