### PR TITLE
Bump k8s-openapi to 0.20.0

### PR DESCRIPTION
**Pull request by clux**
Also bumps minimum kubernetes version.
Standard `just bump-k8s` plus `cargo upgrade -p k8s-openapi -i` and the few readme updates.

Last one before release.

### CODE REVIEW

**Review by nightkr — APPROVED** [review]
SGTM. Might be worth including a note about https://github.com/Arnavion/k8s-openapi/issues/149 in the release notes.

**Comment by clux** [comment]
Ah, yes, will add.

**Comment by Arnavion** [comment]
Out of curiosity, for all the places where you updated the k8s-openapi feature `v1_27` to `v1_28`, why don't you use `latest` ?

If you're worried about `latest` updating to a different version in a semver-compatible update, that won't happen, because adding (or removing) supported versions is always a semver-incompatible change. Not only could that break anyone using `latest`, but also it could break anyone using the version macros.

**Comment by clux** [comment]
Ah, yes. Actually just hadn't gotten around to do it yet. I did just update the [recommendation in our docs](https://kube.rs/kubernetes-version/) yesterday to tell people to use `latest`. And there was also some automation for it in the `justfile` to bump so it has not been a hard job.

Still, nice to clear all that up. Will put up a PR to update it to `latest` as that side is a pretty clear improvement.

By the way, the `earliest` alias is also very nice, and __could__ be very nice for the other side of the range (for testing our minimum supported version), but we are slightly misaligned on our policies (we have currently settled on a 6 version range, and you have 7 - so our MSRV is always +1 of earliest atm). It's probably a bit surprising to folks that we deviate.

Do you have strong feelings about supporting this extended range? It could make k8s-openapi a little more lightweight to drop one. We reasoned that it made sense to follow upstream EOL cycles as per our current https://kube.rs/kubernetes-version/#policy - but if you are not keen on that, we could alternatively increase our range instead.

**Comment by Arnavion** [comment]
My policy is to support the oldest one that public clouds support, per https://github.com/Arnavion/k8s-openapi/blob/master/CONTRIBUTING.md#cloud-offerings . ACK tends to be the oldest one.

**Comment by clux** [comment]
In practice, that looks like it gives you sometimes 7 versions supported, and sometimes 8. At the very least, it would be good to have a consistent answer.

(ACK running 1.22 a full [10 months after upstream maintenance was dropped](https://endoflife.date/kubernetes) is an interesting choice - but i guess all cloud providers lag behind upstream support here to some extent)

**Pull request merged**
