### PR TITLE
Cache `Controller`'s child objects into a reflector

### PR DESCRIPTION
**Pull request by nightkr**
## Motivation

Often, controllers will need to read the objects that they monitor, not just the "main" object. Currently, you can either `Api::get` the child objects, or set up your own reflector and use `applier`. The former is wasteful (since we already have the information from the watches), and the latter has some pretty significant ergonomics downsides.

## Solution

I changed `Controller::owns` and `Controller::watches` to now set up and maintain secondary reflectors, and made them return the `Store`s.

I also ended up changing the rest of `Controller` to use `&mut` references rather than chaining, for consistency. This is a pretty major breaking change, so I'd like to see what people think about the change before updating the docs.

### CODE REVIEW

**Comment by clux** [comment]
I think the idea of doing this makes perfect sense, there are plenty of sensible use-cases where users need to maintain their own cache like things when we already do the watching, and it's definitely wasteful for users to have to double up here. There's also precedent for this in go-land - there's functionality somewhere (either  controller-runtime or client-go) that ensures you only have one set of watchers for an api.

However, and this is going to be a bit of a problem, is that this can dramatically change the memory profile of a controller. It goes from storing one set of objects, to multiple sets ones even in cases where it might not even be needed. So I think if we do this, we should find a way to make it optional when storing it is not necessary. Maybe this can be done by creating something like an optional `Controller::stores(api, store)` thing, or maybe some kind of noop-pass-through mode on the reflector; I don't know. The api here is already complicated so, so expecting this to be a bit hairy to find a good way to weave it in.

**Comment by teozkr** [comment]
Yeah, my first plan was to add it as a separate option, but the cartesian explosion is already getting pretty bad...

**Comment by clux** [comment]
An idea for how to do this that I have been thinking about:

**We could explore changing the `Controller::new`, `Controller::owns`, et al to accept watcher streams**

Users could then apply reflectors as they need outside, and use readers from it. It's more awkward than the proposed one here, 
but it can have the added bonus of allowing us to build something akin to controller [managers](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Manager) where multiple controllers can re-use the same watcher streams without having to do the watch twice. It is possible we could do this if we can pass in [`StreamExt::by_ref`](https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html#method.by_ref) results.

It does come with complications: `Controller::new` spawns the first mandatory reflector store, so this means it is possible to make a double, unnecessary reflector applied to the same stream. We could get around this by making `Controller::new` take both a stream and a `reader` since we don't really need the `writer` part.

<details><summary>It might make the easy mode controller looking a bit uglier though if we are not careful.</summary>
<p>


```rust
let cmgs = Api::<ConfigMapGenerator>::all(client.clone());
let cms = Api::<ConfigMap>::all(client.clone());

Controller::new(cmgs, ListParams::default())
    .owns(cms, ListParams::default())
    .run(reconcile, error_policy, Arc::new(Data { client }))
    .for_each(|res| async move { futures::ok(()) })
    .await;
```

current ^ vs.

```rust
let cmgs = Api::<ConfigMapGenerator>::all(client.clone());
let cms = Api::<ConfigMap>::all(client.clone());

let (reader_gr, writer_gr) = reflector::store();
let (reader_cm, writer_cm) = reflector::store();
let cmgs_stream = reflector(writer_gr, watcher(cmgs, ListParams::default()));
let cms_stream = reflector(writer_cm, watcher(cms, ListParams::default()));

Controller::new(cmgs_stream, reader_gr)
    .owns(cms_stream)
    .run(reconcile, error_policy, Arc::new(Data { client }))
    .for_each(|res| async move { futures::ok(()) })
    .await;
```

and that's not accounting for default backoffs. maybe this is something a controller manager could help reduce the boilerplate of. maybe we could even lift parts of our current api up to a controller-manager.

</p>
</details>

**Comment by teozkr** [comment]
Feels like we're starting to come full circle back to the old `applier` API.. :P

**Comment by clux** [comment]
Reflectors can be made around all controller input streams now since 0.81 via `Controllers::owns_stream` / `Controller::watches_stream` now so this is obsoleted.

**Pull request closed without merging**
