### PR TITLE
tarpaulin bump and simplify config setup

### PR DESCRIPTION
**Pull request by clux**
experiment for #1144 where we can compare against https://app.codecov.io/gh/kube-rs/kube/tree/main/
[config ref](https://github.com/xd009642/tarpaulin/blob/develop/src/config/mod.rs)

### CODE REVIEW

**Comment by tyrone-wu** [comment]
So I forked and modified tarpaulin to address [this issue](https://github.com/kube-rs/kube/issues/1144#issuecomment-2036226357), and it definitely looks like the `#[tokio::test]` it's where the missing coverage went. Now, I'm actually getting `74%`. I'll try to link it here.

**Comment by tyrone-wu** [comment]
Here's the report. This was manually uploaded to codecov.
https://app.codecov.io/gh/tyrone-wu/kube

**Comment by clux** [comment]
Ah, amazing. That looks much better. I see you you have an upstream PR as well 👍

**Comment by clux** [comment]
closed by #1466

**Pull request closed without merging**
