### PR TITLE
chore: Update jsonpath-rust to remove `lazy_static` and `once_cell` dependencies, slight performance improvement

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Motivation

- Removes the number of sub-dependencies and slightly improves performance

## Solution

- Update jsonpath-rust to remove `lazy_static` and `once_cell` dependencies

See diff https://github.com/besok/jsonpath-rust/compare/v0.5...v0.7

image

### CODE REVIEW

**Review by clux — APPROVED** [review]
Nice. Thank you!

**Comment by bryantbiggs** [comment]
I'll fix the failing examples in the morning

**Comment by bryantbiggs** [comment]
looks like the failed lint is because I haven't rebased off `main` to include https://github.com/kube-rs/kube/pull/1636

@clux should I rebase and include this and then we re-run the tests or ok to assume that test is fine and fixed now on `main`?

**Comment by clux** [comment]
All good. DW.

**Pull request merged**
