### PR TITLE
feat: Add storage and served argument to derive macro

### PR DESCRIPTION
**Pull request by Techassi**
This PR adds two new arguments to the derive macro: `storage` and `served`. This allows users to customize these two values in the schema.

## Motivation

Currently it is not possible to customize these two properties using the derive macro because they are hard-coded to be both `true`. Adding support for setting these two properties is highly valuable when a CRD with multiple versions is used.

## Solution

Add two new arguments to make the properties customizable.

### CODE REVIEW

**Comment by clux** [comment]
Hey, thanks for this.

I think this is reasonable, but just wondering if you've seen the [`merge_crd`](https://docs.rs/kube/latest/kube/core/crd/fn.merge_crds.html) fn that aims to help with doing multi-version. If you are setting these flags, then presumably you need to merge your multiple crd schemas anyway, and if you are, perhaps there are things we can do to help with the merge behaviour instead? If not, it would at least be interesting to hear about the use-case.

**Review by clux — APPROVED** [review]

**Comment by clux** [comment]
Okay, yeah, that's way more advanced than I've had to deal with. Happy to send this through. Thank you!

**Comment by Techassi** [comment]
Cool, thanks!

Seems I need to re-format using an older Rust edition (I used my default formatter, which uses newer formatting rules).  Just out of curiosity, why do you still format the code according to the 2018 edition?

**Comment by clux** [comment]
> Just out of curiosity, why do you still format the code according to the 2018 edition?

The important part there is that it's nightly rather than stable, and this forces a custom command rather than LSP defaults. I don't think the edition matters a whole deal, although we should also bump it.

The night things we use are here https://github.com/kube-rs/kube/issues/707 . Sadly they've taken a very long time to stabilise.

**Comment by Techassi** [comment]
> The important part there is that it's nightly rather than stable

Ah, okay! Some of these rules are available in other tooling tho, such as rust-analyzer, but I can see that you don't want to rely on that.

I re-applied the formatting and the CI checks should now succeed.

**Comment by clux** [comment]
Looks great, thank you!

**Comment by Techassi** [comment]
Lovely, thank you as well!

**Comment by Techassi** [comment]
As I know of no better way, I'll just ping you here that I have at least one more PR planned for the derive macro. The upcoming change could also be included in the 0.98.0 release.

Also, what is the timeline for 0.98.0 so that I can plan accordingly?

**Pull request merged**
