### PR TITLE
Add `find_all` method to `Store`

### LINKED ISSUE #1633: Increase flexibility on store public API
### Would you like to work on this feature?

None

### What problem are you trying to solve?

I would like to get a list of objects filtered by a function from a store. I found that just [the find method](https://github.com/kube-rs/kube/blob/9c402a6825e4ca966f74d3d38a65af2d487b6dec/kube-runtime/src/reflector/store.rs#L248) could be similar to my needs. With this method

I can retrieve one item per controller reconcile which is good enough but it could be better.

### Describe the solution you'd like

Expose the `store` attribute or any interface that gives you more flexibility.

### Describe alternatives you've considered

- call the API each time that I need to get those items: more inefficient and complex. Also really don't need it.
- do nothing. Good enough behavior for my use case.

### Documentation, Adoption, Migration Strategy

_No response_

### Target crate for feature

kube-runtime

### PR DESCRIPTION
**Pull request by pando85**
Resolves #1633.

### CODE REVIEW

**Review by clux — APPROVED** [review]
Thanks a lot! LGTM.

(Please disregard lint error, false positive fixed in https://github.com/kube-rs/kube/pull/1636 )

**Comment by SOF3** [comment]
> it requires a collect anyway because store is behind a RwLock.

can't you move the RwLockReadGuard into the returned iterator?

**Comment by pando85** [comment]
I don't understand your point @SOF3 . Could you elaborate on it a bit?

**Comment by SOF3** [comment]
I am just confused why we need so many special methods on `Store` instead of exposing a map-like API that provides `iter()`. Is it simply because we don't want to implement a custom `Iterator` type that owns its own `RwLockReadGuard`?

**Comment by pando85** [comment]
@SOF3 that's a good point. In deed, we already have the `state` method which returns an iterator through all the objects.

I can close this and use that method.

Thank you both.

**Pull request closed without merging**
