### PR TITLE
fix: cargo warning in examples for doc

### PR DESCRIPTION
**Pull request by suryapandian**
The examples are very easy to follow along. Thanks 🙇‍♀️ 

## Motivation
Fixing the code in document

### CODE REVIEW

**Comment by suryapandian** [comment]
oops failing CI, wonder why

**Comment by clux** [comment]
This is actually fixed in `main`: https://github.com/kube-rs/kube/blob/main/kube-runtime/src/watcher.rs#L517

**Comment by suryapandian** [comment]
> This is actually fixed in `main`: https://github.com/kube-rs/kube/blob/main/kube-runtime/src/watcher.rs#L517

the sourcecode link still shows `watcher::Config::default()` but doc.rs is updated tho.
anyways, there is still the unwanted import of `StreamExt` that gives cargo warn :)

**Comment by clux** [comment]
Ah, I see the confusion now.
docs.rs is a bit behind atm because we have an outstanding release.

The link shows `watcher::Config` which is actually correct in `main` due to a recent refactoring.
Closing this.

**Comment by suryapandian** [comment]
i could still fix the cargo warn ...

**Comment by suryapandian** [comment]
cargo warn is fixed in the same branch, if you can reopen the PR

**Comment by clux** [comment]
Thanks, this looks like it works. Don't worry about the test failure. I'll cherry pick this into another PR that's also doing doc changes.

**Comment by suryapandian** [comment]
> Thanks, this looks like it works. Don't worry about the test failure. I'll cherry pick this into another PR that's also doing doc changes.

hmm okay, if this will be handled elsewhere feel free to close the PR. thanks for clarifying

**Comment by clux** [comment]
Picked into #1187. Thanks again.

**Pull request closed without merging**
