### PR TITLE
ObjectList now accepts null metadata like upstream k8s does

### LINKED ISSUE #1491: ListMeta is required in ObjectList wrongly
### Current and expected behavior

We have an API that returns `ObjectList` - k8s parses it correctly while when using kube rs we get deserialization error because metadata is missing.
I couldn't find where Go decides on it, but an example can be seen here with the `+optional` flag.

### Possible solution

Deserialize using the default if NULL

### Additional context

_No response_

### Environment

irrelevant

### Configuration and features

irrelevant

### Affected crates

kube-core

### Would you like to work on fixing this bug?

yes

### PR DESCRIPTION
**Pull request by aviramha**
Fixes #1491

### CODE REVIEW

**Comment by clux** [comment]
you could run it locally with `cargo test -p kube -- derived_resources_discoverable --ignored --nocapture`

**Comment by aviramha** [comment]
Thanks, looking into it.

**Comment by aviramha** [comment]
It worked for me locally when using docker-desktop (not when using a real cluster though)
I suspect it's a flake?

**Comment by clux** [comment]
hm. unlikely. same error on re-run.

**Comment by clux** [comment]
hm, possible hunch: this is the first PR to use k3s 1.30.0 which [released a few days ago](https://github.com/k3s-io/k3s/releases/tag/v1.30.0%2Bk3s1)

**Comment by clux** [comment]
it fails locally on k3s 1.30 🙃

**Comment by clux** [comment]
```
2024-05-13T11:31:55.936900Z  WARN kube_client::client: {"kind":"ValidatingAdmissionPolicyList","apiVersion":"admissionregistration.k8s.io/v1","metadata":{"resourceVersion":"529"}}
, Error("missing field `items`", line: 1, column: 124)
2024-05-13T11:31:55.937000Z TRACE tower::buffer::worker: buffer already closed
2024-05-13T11:31:55.937022Z TRACE mio::poll: deregistering event source from poller
Error: SerdeError(Error("missing field `items`", line: 1, column: 124))
test test::derived_resources_discoverable ... FAILED
```

a list on admission policies returns a list with null'd out items!

this is confirmed with a `kg validatingadmissionpolicies -v=9`:

```
request.go:1212] Response Body: {"kind":"Table","apiVersion":"meta.k8s.io/v1","metadata":{"resourceVersion":"544"},"columnDefinitions":[{"name":"Name","type":"string","format":"name","description":"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names","priority":0},{"name":"Validations","type":"integer","format":"","description":"Validations indicates the number of validation rules defined in this configuration","priority":0},{"name":"ParamKind","type":"string","format":"","description":"ParamKind specifies the kind of resources used to parameterize this policy","priority":0},{"name":"Age","type":"string","format":"","description":"CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.\n\nPopulated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata","priority":0}],"rows":[]}
```

**Comment by aviramha** [comment]
Ah, nice - not sure I'll be able to address the issue (bit problematic for me to setup k3s).

**Comment by aviramha** [comment]
just did :)

**Review by clux — APPROVED** [review]

**Comment by clux** [comment]
Looks sensible to me, I'll merge in, but just out of interest, where did you encounter this? I have not seen this fail before.

**Comment by aviramha** [comment]
Our operator builds `RestfulList` on its own (not sure why we did tbh, maybe no existing modeling in kube-rs? or there wasn't when we needed?) and we don't populate the metadata (because it's optional)

**Comment by clux** [comment]
Oh, it's your stuff? Hm. I do worry that this is kind of incidental then (and not guaranteed to work across all of the go codebase possibly). The protobufs, for instance, do not allow these to be optional ([DeploymentList](https://github.com/kube-rs/k8s-pb/blob/main/k8s-pb-codegen/protos/api/apps/v1/generated.proto#L260-L268), ...[RbacLists](https://github.com/kube-rs/k8s-pb/blob/main/k8s-pb-codegen/protos/api/rbac/v1/generated.proto#L76-L94))

**Comment by aviramha** [comment]
The examples you sent show it's optional?

**Comment by clux** [comment]
:facepalm: I need more sleep. Thought it was the other field. Sorry.

**Comment by clux** [comment]
For future reference the missing `items` in `ValidatingAdmissionPolicy` was indeed a bug upstream and was fixed in 1.30.4

> Fixed a bug in the API server where empty collections of ValidatingAdmissionPolicies did not have an items field. (https://github.com/kubernetes/kubernetes/pull/126146, [@xyz-li](https://github.com/xyz-li)) [SIG API Machinery]

via [1.30.4 changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.30.md#api-change)

**Comment by aviramha** [comment]
> For future reference the missing `items` in `ValidatingAdmissionPolicy` was indeed a bug upstream and was fixed in 1.30.4
> 
> 
> 
> > Fixed a bug in the API server where empty collections of ValidatingAdmissionPolicies did not have an items field. (https://github.com/kubernetes/kubernetes/pull/126146, [@xyz-li](https://github.com/xyz-li)) [SIG API Machinery]
> 
> 
> 
> via [1.30.4 changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.30.md#api-change)

Funny, we can open an issue to revert my PR then when 1.30.4 becomes the minimal supported version.

**Pull request merged**
